version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: my_user
      DATABASE_PASSWORD: my_password
      DATABASE_NAME: my_database
    depends_on:
      - db

volumes:
  db_data:
